WebApplication1/Controllers/AddPostController.cs
using Dominio;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;



namespace WebApplication1.Controllers
{
    public class AddPostController : Controller
    {
        private readonly ILogger<AddPostController> _logger;
        private IWebHostEnvironment _environment;

        public AddPostController(ILogger<AddPostController> logger, IWebHostEnvironment environment)
        {
            _logger = logger;
            _environment = environment;
        }

        public IActionResult AddPost(string mensaje)
        {
            ViewBag.MensajeExito = mensaje;
            return View(new Post());
        }

        [HttpPost]
        public IActionResult AddPost(Post post, IFormFile Image)
        {

            string rutaFisicaWwwRoot = _environment.WebRootPath;
            string nombreImagen = Image.FileName;
            string rutaFisicaFoto = Path.Combine(rutaFisicaWwwRoot, "Images", nombreImagen);
            Miembro miembroLogeado = Sistema.Instancia.GetMiembroByEmail(HttpContext.Session.GetString("usuario"));
            try
            {
                Sistema.Instancia.AgregarPostMiembro(miembroLogeado.Id, post.Titulo, post.Texto, nombreImagen, post.Publico);
                using(FileStream f = new FileStream(rutaFisicaFoto, FileMode.Create))
                {
                    Image.CopyTo(f);
                }
                return RedirectToAction("Index", "Home", new { mensajeExito = "Post creado con exito" });
            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = ex.Message;
                return View();
            }

        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
@using Dominio

@{
    bool ActiveSession = false;
    bool isAdmin = false;
    bool isUsuario = false;
    Miembro usuario = new Miembro();
    Administrador admin = new Administrador();

    if (!string.IsNullOrEmpty(Context.Session.GetString("usuario")))
    {
        admin = Sistema.Instancia.GetAdministradorByEmail(Context.Session.GetString("usuario"));
        usuario = Sistema.Instancia.GetMiembroByEmail(Context.Session.GetString("usuario"));
        ActiveSession = true;
        if (admin is Administrador)
        {
            isAdmin = true;
        }
        if(usuario is Miembro)
        {
            isUsuario = true;
        }
        
    }

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - WebApplication1</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
    </head>
    <body >
        <header class="gradient-right">
            <nav class="gradient-right navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Obligatorio 2</a>

                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                                @if (ActiveSession == true)
                                {
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                                        </li>
                                if(isUsuario == true)
                                    {
                                        <li class="nav-item dropdown">
                                            <a class="nav-link text-dark dropdown-toggle" href="#" id="friendsDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Friends</a>
                                            <div class="dropdown-menu" aria-labelledby="friendsDropdown">
                                                <a class="dropdown-item" asp-area="" asp-controller="ViewFriends" asp-action="ViewFriends">Friends</a>
                                                <a class="dropdown-item" asp-area="" asp-controller="AddFriend" asp-action="AddFriend">Add Friends</a>
                                                <a class="dropdown-item" asp-area="" asp-controller="FriendRequest" asp-action="FriendRequest">Follow Requests</a>

                                            </div>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Search" asp-action="Search">Search</a>
                                        </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="AddPost" asp-action="AddPost">Add a Post</a>
                                    </li>
                                    }
                                if(isAdmin == true)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="ListMembers" asp-action="ListMembers">List Members</a>
                                    </li>
                                }
                               
                            }

                        </ul>
                    </div>
                    @if (ActiveSession == true)
                     { 
                        if (isUsuario == true)
                        {
                            <h2>@usuario.Nombre @usuario.Apellido</h2>
                        }
                        else if (isAdmin == true)
                        {
                            <h2>@admin.Nombre @admin.Apellido Admin</h2>
                        }
                    }
                </div>
            </nav>
        </header>

        <main role="main" class="py-3">
                @RenderBody()
            </main>

        <footer class="border-top footer text-muted gradient-right d-flex justify-content-center">

        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>

}